city_to_state = {
    'All Cities': 'All Cities',

    # 'Andhra Pradesh',

    'Adoni': 'Andhra Pradesh',
    'Amaravati': 'Andhra Pradesh',
    'Anantapur': 'Andhra Pradesh',
    'Chandragiri': 'Andhra Pradesh',
    'Chittoor': 'Andhra Pradesh',
    'Dowlaiswaram': 'Andhra Pradesh',
    'Eluru': 'Andhra Pradesh',
    'Guntur': 'Andhra Pradesh',
    'Kadapa': 'Andhra Pradesh',
    'Kakinada': 'Andhra Pradesh',
    'Kurnool': 'Andhra Pradesh',
    'Machilipatnam': 'Andhra Pradesh',
    'Nagarjunakoṇḍa': 'Andhra Pradesh',
    'Rajahmundry': 'Andhra Pradesh',
    'Srikakulam': 'Andhra Pradesh',
    'Tirupati': 'Andhra Pradesh',
    'Vijayawada': 'Andhra Pradesh',
    'Visakhapatnam': 'Andhra Pradesh',
    'Vizianagaram': 'Andhra Pradesh',
    'Yemmiganur': 'Andhra Pradesh',

    # 'Arunachal Pradesh',

    'Itanagar': 'Arunachal Pradesh',

    # 'Assam',
    'Dhuburi': 'Assam',
    'Dibrugarh': 'Assam',
    'Dispur': 'Assam',
    'Guwahati': 'Assam',
    'Jorhat': 'Assam',
    'Nagaon': 'Assam',
    'Sibsagar': 'Assam',
    'Silchar': 'Assam',
    'Tezpur': 'Assam',
    'Tinsukia': 'Assam',

    # 'Bihar',
    'Ara': 'Bihar',
    'Baruni': 'Bihar',
    'Begusarai': 'Bihar',
    'Bettiah': 'Bihar',
    'Bhagalpur': 'Bihar',
    'Bihar Sharif': 'Bihar',
    'Bodh Gaya': 'Bihar',
    'Buxar': 'Bihar',
    'Chapra': 'Bihar',
    'Darbhanga': 'Bihar',
    'Dehri': 'Bihar',
    'Dinapur Nizamat': 'Bihar',
    'Gaya': 'Bihar',
    'Hajipur': 'Bihar',
    'Jamalpur': 'Bihar',
    'Katihar': 'Bihar',
    'Madhubani': 'Bihar',
    'Motihari': 'Bihar',
    'Munger': 'Bihar',
    'Muzaffarpur': 'Bihar',
    'Patna': 'Bihar',
    'Purnia': 'Bihar',
    'Pusa': 'Bihar',
    'Saharsa': 'Bihar',
    'Samastipur': 'Bihar',
    'Sasaram': 'Bihar',
    'Sitamarhi': 'Bihar',
    'Siwan': 'Bihar',

    # 'Chandigarh',
    'Chandigarh': 'Chandigarh',

    # 'Chhattisgarh',
    'Ambikapur': 'Chhattisgarh',
    'Bhilai': 'Chhattisgarh',
    'Bilaspur': 'Chhattisgarh',
    'Dhamtari': 'Chhattisgarh',
    'Durg': 'Chhattisgarh',
    'Jagdalpur': 'Chhattisgarh',
    'Raipur': 'Chhattisgarh',
    'Rajnandgaon': 'Chhattisgarh',

    #'Dadra And Nagar Haveli (Union Territory)',
    'Silvassa': 'Dadra And Nagar Haveli (Union Territory)',
    'Dadra And Nagar Haveli (Union Territory)': 'Dadra And Nagar Haveli (Union Territory)',

    #'Daman And Diu (Union Territory)',
    'Daman': 'Daman And Diu (Union Territory)',
    'Diu': 'Daman And Diu (Union Territory)',

    # 'Delhi',
    'Delhi': 'Delhi',
    'Delhi NCR': 'Delhi',

    # 'Goa',
    'Madgaon': 'Goa',
    'Panaji': 'Goa',

    # 'Gujarat',
    'Ahmedabad': 'Gujarat',
    'Amreli': 'Gujarat',
    'Bharuch': 'Gujarat',
    'Bhavnagar': 'Gujarat',
    'Bhuj': 'Gujarat',
    'Dwarka': 'Gujarat',
    'Gandhinagar': 'Gujarat',
    'Godhra': 'Gujarat',
    'Jamnagar': 'Gujarat',
    'Junagadh': 'Gujarat',
    'Kandla': 'Gujarat',
    'Khambhat': 'Gujarat',
    'Kheda': 'Gujarat',
    'Mahesana': 'Gujarat',
    'Morvi': 'Gujarat',
    'Nadiad': 'Gujarat',
    'Navsari': 'Gujarat',
    'Okha': 'Gujarat',
    'Palanpur': 'Gujarat',
    'Patan': 'Gujarat',
    'Porbandar': 'Gujarat',
    'Rajkot': 'Gujarat',
    'Surat': 'Gujarat',
    'Surendranagar': 'Gujarat',
    'Valsad': 'Gujarat',
    'Veraval': 'Gujarat',

    # 'Haryana',
    'Ambala': 'Haryana',
    'Bhiwani': 'Haryana',
    'Gurugram': 'Haryana',
    'Faridabad': 'Haryana',
    'Firozpur Jhirka': 'Haryana',
    'Gurgaon': 'Haryana',
    'Hansi': 'Haryana',
    'Hisar': 'Haryana',
    'Jind': 'Haryana',
    'Kaithal': 'Haryana',
    'Karnal': 'Haryana',
    'Kurukshetra': 'Haryana',
    'Panipat': 'Haryana',
    'Panchkula': 'Haryana',
    'Pehowa': 'Haryana',
    'Rewari': 'Haryana',
    'Rohtak': 'Haryana',
    'Sirsa': 'Haryana',
    'Sonipat': 'Haryana',

    #'Himachal Pradesh',
    'Bilaspur': 'Himachal Pradesh',
    'Chamba': 'Himachal Pradesh',
    'Dalhousie': 'Himachal Pradesh',
    'Dharmshala': 'Himachal Pradesh',
    'Hamirpur': 'Himachal Pradesh',
    'Kangra': 'Himachal Pradesh',
    'Kullu': 'Himachal Pradesh',
    'Mandi': 'Himachal Pradesh',
    'Nahan': 'Himachal Pradesh',
    'Shimla': 'Himachal Pradesh',
    'Una': 'Himachal Pradesh',

    # 'Jammu And Kashmir (Union Territory)',,
                'Anantnag': 'Jammu And Kashmir (Union Territory)',
                'Baramula': 'Jammu And Kashmir (Union Territory)',
                'Doda': 'Jammu And Kashmir (Union Territory)',
                'Gulmarg': 'Jammu And Kashmir (Union Territory)',
                'Jammu': 'Jammu And Kashmir (Union Territory)',
                'Kathua': 'Jammu And Kashmir (Union Territory)',
                'Punch': 'Jammu And Kashmir (Union Territory)',
                'Rajauri': 'Jammu And Kashmir (Union Territory)',
                'Srinagar': 'Jammu And Kashmir (Union Territory)',
                'Udhampur': 'Jammu And Kashmir (Union Territory)',
    # 'Jharkhand',
                'Bokaro': 'Jharkhand',
                'Chaibasa': 'Jharkhand',
                'Deoghar': 'Jharkhand',
                'Dhanbad': 'Jharkhand',
                'Dumka': 'Jharkhand',
                'Giridih': 'Jharkhand',
                'Hazaribag': 'Jharkhand',
                'Jamshedpur': 'Jharkhand',
                'Jharia': 'Jharkhand',
                'Rajmahal': 'Jharkhand',
                'Ranchi': 'Jharkhand',
                'Saraikela': 'Jharkhand',
    # 'Karnataka',
                'Badami': 'Karnataka',
                'Ballari': 'Karnataka',
                'Bangalore': 'Karnataka',
                'Bengaluru': 'Karnataka',
                'Belgavi': 'Karnataka',
                'Bhadravati': 'Karnataka',
                'Bidar': 'Karnataka',
                'Chikkamagaluru': 'Karnataka',
                'Chitradurga': 'Karnataka',
                'Davangere': 'Karnataka',
                'Halebid': 'Karnataka',
                'Hassan': 'Karnataka',
                'Hubballi-Dharwad': 'Karnataka',
                'Kalaburagi': 'Karnataka',
                'Kolar': 'Karnataka',
                'Madikeri': 'Karnataka',
                'Mandya': 'Karnataka',
                'Mangaluru': 'Karnataka',
                'Mysuru': 'Karnataka',
                'Raichur': 'Karnataka',
                'Shivamogga': 'Karnataka',
                'Shravanabelagola': 'Karnataka',
                'Shrirangapattana': 'Karnataka',
                'Tumkuru': 'Karnataka',
    # 'Kerala',,
                'Alappuzha': 'Kerala',
                'Badagara': 'Kerala',
                'Idukki': 'Kerala',
                'Kannur': 'Kerala',
                'Kochi': 'Kerala',
                'Kollam': 'Kerala',
                'Kottayam': 'Kerala',
                'Kozhikode': 'Kerala',
                'Mattancheri': 'Kerala',
                'Palakkad': 'Kerala',
                'Thalassery': 'Kerala',
                'Thiruvananthapuram': 'Kerala',
                'Thrissur': 'Kerala',

    # 'Ladakh',
                'Kargil': 'Ladakh',
                'Leh': 'Ladakh',

    # 'Madhya Pradesh',
                'Balaghat': 'Madhya Pradesh',
                'Barwani': 'Madhya Pradesh',
                'Betul': 'Madhya Pradesh',
                'Bharhut': 'Madhya Pradesh',
                'Bhind': 'Madhya Pradesh',
                'Bhojpur': 'Madhya Pradesh',
                'Bhopal': 'Madhya Pradesh',
                'Burhanpur': 'Madhya Pradesh',
                'Chhatarpur': 'Madhya Pradesh',
                'Chhindwara': 'Madhya Pradesh',
                'Damoh': 'Madhya Pradesh',
                'Datia': 'Madhya Pradesh',
                'Dewas': 'Madhya Pradesh',
                'Dhar': 'Madhya Pradesh',
                'Guna': 'Madhya Pradesh',
                'Gwalior': 'Madhya Pradesh',
                'Hoshangabad': 'Madhya Pradesh',
                'Indore': 'Madhya Pradesh',
                'Itarsi': 'Madhya Pradesh',
                'Jabalpur': 'Madhya Pradesh',
                'Jhabua': 'Madhya Pradesh',
                'Khajuraho': 'Madhya Pradesh',
                'Khandwa': 'Madhya Pradesh',
                'Khargon': 'Madhya Pradesh',
                'Maheshwar': 'Madhya Pradesh',
                'Mandla': 'Madhya Pradesh',
                'Mandsaur': 'Madhya Pradesh',
                'Mhow': 'Madhya Pradesh',
                'Morena': 'Madhya Pradesh',
                'Murwara': 'Madhya Pradesh',
                'Narsimhapur': 'Madhya Pradesh',
                'Narsinghgarh': 'Madhya Pradesh',
                'Narwar': 'Madhya Pradesh',
                'Neemuch': 'Madhya Pradesh',
                'Nowgong': 'Madhya Pradesh',
                'Orchha': 'Madhya Pradesh',
                'Panna': 'Madhya Pradesh',
                'Raisen': 'Madhya Pradesh',
                'Rajgarh': 'Madhya Pradesh',
                'Ratlam': 'Madhya Pradesh',
                'Rewa': 'Madhya Pradesh',
                'Sagar': 'Madhya Pradesh',
                'Sarangpur': 'Madhya Pradesh',
                'Satna': 'Madhya Pradesh',
                'Sehore': 'Madhya Pradesh',
                'Seoni': 'Madhya Pradesh',
                'Shahdol': 'Madhya Pradesh',
                'Shajapur': 'Madhya Pradesh',
                'Sheopur': 'Madhya Pradesh',
                'Shivpuri': 'Madhya Pradesh',
                'Ujjain': 'Madhya Pradesh',
                'Vidisha': 'Madhya Pradesh',

    # 'Maharashtra',
                'Ahmadnagar': 'Maharashtra',
                'Akola': 'Maharashtra',
                'Amravati': 'Maharashtra',
                'Aurangabad': 'Maharashtra',
                'Bhandara': 'Maharashtra',
                'Bhusawal': 'Maharashtra',
                'Bid': 'Maharashtra',
                'Buldana': 'Maharashtra',
                'Chandrapur': 'Maharashtra',
                'Daulatabad': 'Maharashtra',
                'Dhule': 'Maharashtra',
                'Jalgaon': 'Maharashtra',
                'Kalyan': 'Maharashtra',
                'Karli': 'Maharashtra',
                'Kolhapur': 'Maharashtra',
                'Mahabaleshwar': 'Maharashtra',
                'Malegaon': 'Maharashtra',
                'Matheran': 'Maharashtra',
                'Mumbai': 'Maharashtra',
                'Nagpur': 'Maharashtra',
                'Nanded': 'Maharashtra',
                'Nashik': 'Maharashtra',
                'Osmanabad': 'Maharashtra',
                'Pandharpur': 'Maharashtra',
                'Parbhani': 'Maharashtra',
                'Pune': 'Maharashtra',
                'Ratnagiri': 'Maharashtra',
                'Sangli': 'Maharashtra',
                'Satara': 'Maharashtra',
                'Sevagram': 'Maharashtra',
                'Solapur': 'Maharashtra',
                'Thane': 'Maharashtra',
                'Ulhasnagar': 'Maharashtra',
                'Vasai-Virar': 'Maharashtra',
                'Wardha': 'Maharashtra',
                'Yavatmal': 'Maharashtra',
    # 'Manipur',
                'Imphal': 'Manipur',

    # 'Meghalaya',
                'Cherrapunji': 'Meghalaya',
                'Shillong': 'Meghalaya',
                'Mizoram': 'Meghalaya',
                'Aizawl': 'Meghalaya',
                'Lunglei': 'Meghalaya',

    # 'Nagaland',,
                'Kohima': 'Nagaland',
                'Mon': 'Nagaland',
                'Phek': 'Nagaland',
                'Wokha': 'Nagaland',
                'Zunheboto': 'Nagaland',

    # 'Odisha',
                'Balangir': 'Odisha',
                'Baleshwar': 'Odisha',
                'Baripada': 'Odisha',
                'Bhubaneshwar': 'Odisha',
                'Brahmapur': 'Odisha',
                'Cuttack': 'Odisha',
                'Dhenkanal': 'Odisha',
                'Keonjhar': 'Odisha',
                'Konark': 'Odisha',
                'Koraput': 'Odisha',
                'Paradip': 'Odisha',
                'Phulabani': 'Odisha',
                'Puri': 'Odisha',
                'Sambalpur': 'Odisha',
                'Udayagiri': 'Odisha',

    # 'Pondicherry',

                'Karaikal': 'Pondicherry',
                'Mahe': 'Pondicherry',
                'Pondicherry': 'Pondicherry',
                'Yanam': 'Pondicherry',

    # 'Punjab',
                'Amritsar': 'Punjab',
                'Batala': 'Punjab',
                'Chandigarh': 'Punjab',
                'Faridkot': 'Punjab',
                'Firozpur': 'Punjab',
                'Gurdaspur': 'Punjab',
                'Hoshiarpur': 'Punjab',
                'Jalandhar': 'Punjab',
                'Kapurthala': 'Punjab',
                'Ludhiana': 'Punjab',
                'Nabha': 'Punjab',
                'Patiala': 'Punjab',
                'Rupnagar': 'Punjab',
                'Sangrur': 'Punjab',

    # 'Rajasthan',
                'Abu': 'Rajasthan',
                'Ajmer': 'Rajasthan',
                'Alwar': 'Rajasthan',
                'Amer': 'Rajasthan',
                'Barmer': 'Rajasthan',
                'Beawar': 'Rajasthan',
                'Bharatpur': 'Rajasthan',
                'Bhilwara': 'Rajasthan',
                'Bikaner': 'Rajasthan',
                'Bundi': 'Rajasthan',
                'Chittaurgarh': 'Rajasthan',
                'Churu': 'Rajasthan',
                'Dhaulpur': 'Rajasthan',
                'Dungarpur': 'Rajasthan',
                'Ganganagar': 'Rajasthan',
                'Hanumangarh': 'Rajasthan',
                'Jaipur': 'Rajasthan',
                'Jaisalmer': 'Rajasthan',
                'Jalor': 'Rajasthan',
                'Jhalawar': 'Rajasthan',
                'Jhunjhunu': 'Rajasthan',
                'Jodhpur': 'Rajasthan',
                'Kishangarh': 'Rajasthan',
                'Kota': 'Rajasthan',
                'Merta': 'Rajasthan',
                'Nagaur': 'Rajasthan',
                'Nathdwara': 'Rajasthan',
                'Pali': 'Rajasthan',
                'Phalodi': 'Rajasthan',
                'Pushkar': 'Rajasthan',
                'Sawai Madhopur': 'Rajasthan',
                'Shahpura': 'Rajasthan',
                'Sikar': 'Rajasthan',
                'Sirohi': 'Rajasthan',
                'Tonk': 'Rajasthan',
                'Udaipur': 'Rajasthan',
    # 'Sikkim',
                'Gangtok': 'Sikkim',
                'Gyalsing': 'Sikkim',
                'Lachung': 'Sikkim',
                'Mangan': 'Sikkim',

    # 'Tamil Nadu',
                'Arcot': 'Tamil Nadu',
                'Chengalpattu': 'Tamil Nadu',
                'Chennai': 'Tamil Nadu',
                'Chidambaram': 'Tamil Nadu',
                'Coimbatore': 'Tamil Nadu',
                'Cuddalore': 'Tamil Nadu',
                'Dharmapuri': 'Tamil Nadu',
                'Dindigul': 'Tamil Nadu',
                'Erode': 'Tamil Nadu',
                'Kanchipuram': 'Tamil Nadu',
                'Kanniyakumari': 'Tamil Nadu',
                'Kodaikanal': 'Tamil Nadu',
                'Kumbakonam': 'Tamil Nadu',
                'Madurai': 'Tamil Nadu',
                'Mamallapuram': 'Tamil Nadu',
                'Nagappattinam': 'Tamil Nadu',
                'Nagercoil': 'Tamil Nadu',
                'Palayankottai': 'Tamil Nadu',
                'Pudukkottai': 'Tamil Nadu',
                'Rajapalaiyam': 'Tamil Nadu',
                'Ramanathapuram': 'Tamil Nadu',
                'Salem': 'Tamil Nadu',
                'Thanjavur': 'Tamil Nadu',
                'Tiruchchirappalli': 'Tamil Nadu',
                'Tirunelveli': 'Tamil Nadu',
                'Tiruppur': 'Tamil Nadu',
                'Tuticorin': 'Tamil Nadu',
                'Udhagamandalam': 'Tamil Nadu',
                'Vellore': 'Tamil Nadu',

             # 'Telangana',,
                'Hyderabad': 'Telangana',
                'Karimnagar': 'Telangana',
                'Khammam': 'Telangana',
                'Mahbubnagar': 'Telangana',
                'Nizamabad': 'Telangana',
                'Sangareddi': 'Telangana',
                'Warangal': 'Telangana',

    # 'Tripura',,
                'Agartala': 'Tripura',

    # 'Uttar Pradesh',
                'Agra': 'Uttar Pradesh',
                'Aligarh': 'Uttar Pradesh',
                'Amroha': 'Uttar Pradesh',
                'Ayodhya': 'Uttar Pradesh',
                'Azamgarh': 'Uttar Pradesh',
                'Bahraich': 'Uttar Pradesh',
                'Ballia': 'Uttar Pradesh',
                'Banda': 'Uttar Pradesh',
                'Bara Banki': 'Uttar Pradesh',
                'Bareilly': 'Uttar Pradesh',
                'Basti': 'Uttar Pradesh',
                'Bijnor': 'Uttar Pradesh',
                'Bithur': 'Uttar Pradesh',
                'Budaun': 'Uttar Pradesh',
                'Bulandshahr': 'Uttar Pradesh',
                'Deoria': 'Uttar Pradesh',
                'Etah': 'Uttar Pradesh',
                'Etawah': 'Uttar Pradesh',
                'Faizabad': 'Uttar Pradesh',
                'Farrukhabad-cum-Fatehgarh': 'Uttar Pradesh',
                'Fatehpur': 'Uttar Pradesh',
                'Fatehpur Sikri': 'Uttar Pradesh',
                'Ghaziabad': 'Uttar Pradesh',
                'Ghazipur': 'Uttar Pradesh',
                'Gonda': 'Uttar Pradesh',
                'Gorakhpur': 'Uttar Pradesh',
                'Hamirpur': 'Uttar Pradesh',
                'Hardoi': 'Uttar Pradesh',
                'Hathras': 'Uttar Pradesh',
                'Jalaun': 'Uttar Pradesh',
                'Jaunpur': 'Uttar Pradesh',
                'Jhansi': 'Uttar Pradesh',
                'Kannauj': 'Uttar Pradesh',
                'Kanpur': 'Uttar Pradesh',
                'Lakhimpur': 'Uttar Pradesh',
                'Lalitpur': 'Uttar Pradesh',
                'Lucknow': 'Uttar Pradesh',
                'Mainpuri': 'Uttar Pradesh',
                'Mathura': 'Uttar Pradesh',
                'Meerut': 'Uttar Pradesh',
                'Mirzapur-Vindhyachal': 'Uttar Pradesh',
                'Moradabad': 'Uttar Pradesh',
                'Muzaffarnagar': 'Uttar Pradesh',
                'Noida': 'Uttar Pradesh',
                'Partapgarh': 'Uttar Pradesh',
                'Pilibhit': 'Uttar Pradesh',
                'Prayagraj': 'Uttar Pradesh',
                'Rae Bareli': 'Uttar Pradesh',
                'Rampur': 'Uttar Pradesh',
                'Saharanpur': 'Uttar Pradesh',
                'Sambhal': 'Uttar Pradesh',
                'Shahjahanpur': 'Uttar Pradesh',
                'Sitapur': 'Uttar Pradesh',
                'Sultanpur': 'Uttar Pradesh',
                'Tehri': 'Uttar Pradesh',
                'Varanasi': 'Uttar Pradesh',

    # 'Uttarakhand',,
                'Almora': 'Uttarakhand',
                'Dehra Dun': 'Uttarakhand',
                'Haridwar': 'Uttarakhand',
                'Mussoorie': 'Uttarakhand',
                'Nainital': 'Uttarakhand',
                'Pithoragarh': 'Uttarakhand',

    # 'West Bengal',,
                'Alipore': 'West Bengal',
                'Alipur Duar': 'West Bengal',
                'Asansol': 'West Bengal',
                'Baharampur': 'West Bengal',
                'Bally': 'West Bengal',
                'Balurghat': 'West Bengal',
                'Bankura': 'West Bengal',
                'Baranagar': 'West Bengal',
                'Barasat': 'West Bengal',
                'Barrackpore': 'West Bengal',
                'Basirhat': 'West Bengal',
                'Bhatpara': 'West Bengal',
                'Bishnupur': 'West Bengal',
                'Budge Budge': 'West Bengal',
                'Burdwan': 'West Bengal',
                'Chandernagore': 'West Bengal',
                'Darjiling': 'West Bengal',
                'Diamond Harbour': 'West Bengal',
                'Dum Dum': 'West Bengal',
                'Durgapur': 'West Bengal',
                'Halisahar': 'West Bengal',
                'Haora': 'West Bengal',
                'Hugli': 'West Bengal',
                'Ingraj Bazar': 'West Bengal',
                'Jalpaiguri': 'West Bengal',
                'Kalimpong': 'West Bengal',
                'Kamarhati': 'West Bengal',
                'Kanchrapara': 'West Bengal',
                'Kharagpur': 'West Bengal',
                'Koch Kolkata': 'West Bengal',
                'Krishnanagar': 'West Bengal',
                'Malda': 'West Bengal',
                'Midnapore': 'West Bengal',
                'Murshidabad': 'West Bengal',
                'Navadwip': 'West Bengal',
                'Palashi': 'West Bengal',
                'Panihati': 'West Bengal',
                'Purulia': 'West Bengal',
                'Raiganj': 'West Bengal',
                'Santipur': 'West Bengal',
                'Shantiniketan': 'West Bengal',
                'Shrirampur': 'West Bengal',
                'Siliguri': 'West Bengal',
                'Siuri': 'West Bengal',
                'Tamluk': 'West Bengal',
                'Titagarh': 'West Bengal',
}
