sub_types_to_type = {
  'New Cylinder': 'Oxygen',
  'Refill': 'Oxygen',
  'Concentrator': 'Oxygen',
  'ICU Bed': 'Hospital Beds',
  'Ventilator Bed': 'Hospital Beds',
  'Oxygen Beds': 'Hospital Beds',
  'Non Oxygen Beds': 'Hospital Beds',
  'Remdesivir': 'Medicines Injections',
  'Fabiflu': 'Medicines Injections',
  'Tocilizumab': 'Medicines Injections',
  'Normal Life Support': 'Ambulances',
  'Advanced Life Support': 'Ambulances',
  'Plasma': 'Blood',
  'Blood': 'Blood',
  'Home ICU Setup': 'Home Care',
  'Nursing Staff': 'Home Care',
  'Home Testing': 'Testing',
  'Lab Testing': 'Testing',
  'Tiffin Service': 'Food Tiffin',
  'Meal Provider': 'Food Tiffin',
}
